backend:
  name: git-gateway
  branch: staging

local_backend: true

media_folder: "content/uploads"   # where uploaded files are stored in the repo
public_folder: "/uploads"         # how those files are served on the site

collections:

  # Header and Footer settings
  - name: "settings"
    label: "Header and Footer"
    files:
      - label: "âš™ï¸ Header (navigation) and Footer Settings"
        name: "site"
        file: "./_data/site.yml"
        fields:
          # Header
          - { label: "Site Title", name: "title", widget: "string" }
          - label: "Navigation"
            name: "nav"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          # Footer
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
              - { label: "Site information", name: "info", widget: "string" }

  # Landing page
  - name: "landing"
    label: "Landing Page"
    files:
      - file: "content/landing/landing.md"
        label: "Landing Content"
        name: "landing"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  # About page
  - name: "about"
    label: "About Page"
    files:
      - file: "content/about/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  # Contact page
  - name: "contact"
    label: "Contact Page"
    files:
      - file: "content/contact/contact.md"
        label: "Contact Content"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  # Projects (folder-based)
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    extension: "md"
    fields:
      - { label: "ğŸ–¼ï¸ Page Layout (DON'T CHANGE)", name: "layout", widget: "hidden", default: "_pages/project_page.njk" }

      - { label: "ğŸ“Œ Project Title", name: "title", widget: "string" }
      - { label: "âœï¸ Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "â„¹ï¸ Info Tag", name: "info", widget: "string", required: false }

      - { label: "ğŸ“… Year", name: "year", widget: "number", value_type: "int" }
      - { label: "ğŸ“† Full Date (sorting)", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }

      - label: "ğŸ–¼ï¸ Thumbnail Image"
        name: "thumbnail"
        widget: "image" 
        hint: "Upload or select the main project image."

      - { label: "âœï¸ Image Description (for accessibility)", name: "imageAlt", widget: "string"}

      - { label: "ğŸ“ Highlight?", name: "highlight", widget: "boolean", default: false }

      - { label: "ğŸ‘‹ Project Content", name: "body", widget: "markdown" }
